apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: lsy8ygzkf-nodejs
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: lsy8ygzkf-nodejs 
  name: lsy8ygzkf-nodejs
spec:
  ports:
  - port: 3001 
    targetPort: 3001 
  selector:
    app.kubernetes.io/instance: lsy8ygzkf-nodejs 
